# Mailinglist schema

# --- !Ups

create table "Mailinglists" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "email" varchar(255) not null,
  "name" varchar(255) not null
);

create table "Users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "email" varchar(255) not null,
  "name" varchar(255) not null,
  "password" varchar(255) not null
);

create table "MailinglistMembers" (
  "MailinglistId" bigint not null,
  "UserId" bigint not null,
  "IsApproved" bit not null default 0,
  "IsActive" bit not null default 0,
  primary key("MailinglistId", "UserId"),
  foreign key("MailinglistId") references "Mailinglists"("id") on delete cascade,
  foreign key("UserId") references "Users"("id") on delete cascade
);

# --- !Downs

drop table if exists "MailinglistMembers";
drop table if exists "Users";
drop table if exists "Mailinglists";
