# Mailinglist schema

# --- !Ups

create table "Mailinglists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "email" varchar(255) not null
);

create table "Users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "email" varchar(255) not null,
  "name" varchar(255) not null,
  "password" varchar(255) not null
);

create table "MailinglistMembers" (
  "MailinglistId" varchar(255) not null,
  "UserId" varchar(255) not null,
  primary key("MailinglistId", "UserId"),
  foreign key("MailinglistId") references "Mailinglists"("id") on delete cascade,
  foreign key("UserId") references "Users"("id") on delete cascade
);

# --- !Downs

drop table if exists "MailinglistMembers";
drop table if exists "Users";
drop table if exists "Mailinglists";
